import React from 'react';
import image from '../img/slideshowimgs/img1.jpg'
import './stylesheets/research.css'
import Biomechanics from './researchConstants/Biomechanics';
import Population from './researchConstants/PopDynamics';
import Education from './researchConstants/Education';
import Behavior from './researchConstants/BehaviorAndNeuro';
import {Link} from 'react-scroll';
import { useMediaQuery } from 'react-responsive';

const text = "We look at Hydra, as not only can they regenerate from small tissue pieces, but they can also regenerate from cell aggregates after disintegration into individual cells. We can study the biomechanics of this process of self-organization for insights into development. We also study the biomechanics of Hydra’s feeding response, as there are large epithelial deformations during both feeding and regeneration that allow us to look at epithelial mechanics. We use experimental tools and image analysis to characterize both processes and develop computational and analytical models to explain them" +
"Planarians reproduce asexually by ripping themselves into two pieces which regenerate into two new worms. How they manage to generate stresses high enough to rupture using only forces generated by their own musculature is a fascinating problem. We study how different species of planarians solve this problem."

function Research() {
    const isComputer = useMediaQuery({minDeviceWidth: 1224})
    return (
        <div>
            <div style={{
                    backgroundImage: `url(${image})`,
                    height: "100%",
                    backgroundPosition: 'center',
                    backgroundRepeat: 'no-repeat',
                    backgroundSize: 'cover',
                    
            }}>
                    <div className = "TandT">
                        <div className="researchTitle">
                            <h5 className= {isComputer ? "research" : "research-small"}>Research</h5>
                        </div>
                        <div className = {isComputer ? "subtitles" : "subtitles-small"}>
                            <h3 className = 'projects-small'>
                                <Link 
                                    to = "biomechanics"
                                    smooth={true} 
                                    duration={500}
                                    className= {isComputer ? "projects" : "projects-small"}
                                >
                                    Biomechanics
                                </Link>
                            </h3>
                            <h3>  
                                <Link 
                                    to = "behavior"
                                    smooth={true} 
                                    duration={500}
                                    className= {isComputer ? "projects" : "projects-small"}
                                >
                                    Behavior and Neurotoxicology
                                </Link>
                            </h3>
                            <h3>  
                                <Link 
                                    to = "population"
                                    smooth={true} 
                                    duration={500}
                                    className= {isComputer ? "projects" : "projects-small"}
                                >
                                    Population Dynamics
                                </Link>
                            </h3>
                            <h3>  
                                <Link 
                                    to = "education"
                                    smooth={true} 
                                    duration={500}
                                    className= {isComputer ? "projects" : "projects-small"}
                                >
                                    Science Education
                                </Link>
                            </h3>
                        </div>
                    </div>
            </div>

            <Biomechanics image={image} isComputer={isComputer}/>
            <Behavior image={image} isComputer={isComputer}/>
            <Population image={image} isComputer={isComputer}/>
            <Education image={image} isComputer={isComputer}/>
    
        </div>
    );
}
 
export default Research;